use-grep

diff --git a/.github/workflows/docsbot-deploy-site.yml b/.github/workflows/docsbot-deploy-site.yml
--- a/.github/workflows/docsbot-deploy-site.yml
+++ b/.github/workflows/docsbot-deploy-site.yml
@@ -14,10 +14,10 @@ jobs:
         env:
           ISSUE_TITLE: ${{ github.event.issue.title }}
         run: |
-          if ! [[ "$ISSUE_TITLE" =~ ^[a-zA-Z0-9 _-]{1,100}$ ]]; then
-            echo "Issue title contains invalid characters or is too long."
-            exit 1
-          fi
+         if ! echo "$ISSUE_TITLE" | grep -qE "^[a-zA-Z0-9 _-]{1,100}$"; then
+          echo "Issue title contains invalid characters or is too long."
+          exit 1
+         fi
 
       - name: URL encode title
         id: url_encode_title
